import us.nebula.gradle.Util

buildscript {
    repositories {
        mavenCentral()
        maven {
            name = "forge"
            url = "https://maven.minecraftforge.net/"
        }
        maven { url 'https://repo.spongepowered.org/maven' }
    }
    dependencies {
        classpath ("com.anatawa12.forge:ForgeGradle:$project.forge_gradle_version") {
            changing = true
        }
    }
}

plugins {
    id 'java-library'
    id 'com.github.gmazzo.buildconfig' version "$build_config_version"
}

configurations.configureEach {
    resolutionStrategy.eachDependency { DependencyResolveDetails details ->
        // ooga booga
        if (details.requested.group == 'org.lwjgl.lwjgl') {
            details.useVersion project.lwjgl_version
        }
        // i hate old ass versions of java
        if (details.requested.group == 'org.ow2.asm') {
            details.useVersion project.asm_version
        }
    }
}

apply plugin: 'forge'

var buildNumber = project.build_id.toInteger()
var gitHash = Util.execute("git rev-parse --short HEAD", "error")
var gitBranch = Util.execute("git branch --show-current", "main")

group = project.group
version = project.version

buildConfig {
    buildConfigField(String,  "HASH", gitHash)
    buildConfigField(String,  "BRANCH", gitBranch)
    buildConfigField(String,  "VERSION", project.version)
    buildConfigField(Integer, "BUILD", buildNumber)
    buildConfigField(String,  "BUILD_TIME", "${new Date(System.currentTimeMillis()).format("MM/dd/yyyy HH:mm")}")
    buildConfigField(String,  "NAME", project.name)
    buildConfigField("${project.group}.Environment", "ENV", "${project.group}.Environment.${project.env.toUpperCase()}")

    packageName project.group.toString()
    useJavaOutput()
    generateAtSync = true
}

sourceSets.main.java.srcDirs += "build/gen/buildconfig/src/main"

compileJava {
    sourceCompatibility = targetCompatibility = '1.8'
    options.encoding 'UTF-8'
}

configurations {
    jarLib
    implementation.extendsFrom(jarLib)
    configureEach {
        resolutionStrategy {
            force "org.lwjgl.lwjgl:lwjgl-platform:2.9.4-nightly-20150209"

            force "org.ow2.asm:asm:5.2"
            force "org.ow2.asm:asm-tree:5.2"
            force "org.ow2.asm:asm-commons:5.2"
            force "org.ow2.asm:asm-debug-all:5.2"
        }
    }
}

minecraft {
    version = project.minecraft_version + '-' + project.forge_version
    runDir = "run"
}

def refMap = "${tasks.compileJava.temporaryDir}" + File.separator + "mixins.nebula.refmap.json"
def mixinSrg = "${tasks.reobf.temporaryDir}" + File.separator + "mixins.srg"
afterEvaluate {
    tasks.matching { it.name == "sourceMainJava" }.configureEach {
        dependsOn(generateBuildConfig)
    }

    tasks.withType(JavaCompile).configureEach {
        options.compilerArgs += ["-AreobfSrgFile=${tasks.reobf.srg}",
                                 "-AoutSrgFile=${mixinSrg}",
                                 "-AoutRefMapFile=${refMap}"]
    }

    tasks.withType(JavaExec).configureEach {
        jvmArgs "-Dfml.coreMods.load=ez.nebula.client.forge.NebulaFMLCoreModPlugin"
        jvmArgs "-Dfml.ignoreModNames=true"
    }
}

reobf {
    addExtraSrgFile mixinSrg
}

repositories {
    mavenCentral()
    maven { url 'https://repo.spongepowered.org/maven' }
}

dependencies {
    jarLib("org.spongepowered:mixin:$project.mixin_version") {
        exclude module: 'launchwrapper'
        exclude module: 'guava'
        exclude module: 'gson'
        exclude module: 'commons-io'
    }
    annotationProcessor("org.spongepowered:mixin:$project.mixin_annotation_processor_version:processor") {
        exclude module: 'gson'
    }

    // jarLib "org.java-websocket:Java-WebSocket:$project.jws_version"
    jarLib "com.mojang:brigadier:$project.brigadier_version"
}

tasks.withType(Jar).configureEach {
    from {
        configurations.jarLib
                .collect { it.isDirectory() ? it : zipTree(it) }
    }
    exclude 'dummyThing',
            'LICENSE.txt',
            'META-INF/MUMFREY.RSA',
            'META-INF/maven/**',
            'org/**/*.html'
    from refMap

    duplicatesStrategy = DuplicatesStrategy.INCLUDE
    manifest.attributes(
            'FMLCorePluginContainsFMLMod': true,
            'FMLCorePlugin': 'ez.nebula.client.forge.NebulaFMLCoreModPlugin',
            'ForceLoadAsMod': true,
            'MainClass': 'ez.nebula.client.installer.NebulaForgeInstallerMain'
            // 'FMLAT': 'nebula_AT.cfg',
    )
}

processResources {
    inputs.property "version", project.version
    inputs.property "mcversion", project.minecraft.version
    filesMatching('mcmod.info') {
        expand 'version': project.version, 'mcversion': project.minecraft.version
    }
}

reobf {
    addExtraSrgFile mixinSrg
}