version=4.0.0
build_id=95
env=public_beta
group=ez.nebula.client

# Build versions
forge_gradle_version=1.2-1.1.+
build_config_version=5.5.4
mixin_gradle_version=0.6-SNAPSHOT

# Versions
lwjgl_version=2.9.4-nightly-20150209
brigadier_version=1.0.18
jws_version=1.6.0
asm_version=5.2

# Forge properties
minecraft_version=1.7.2
forge_version=10.12.2.1161-mc172

# Mixin versions
mixin_version=0.7.11-SNAPSHOT
mixin_annotation_processor_version=0.8.2